# 测试环境配置 - Spring Boot 3.x

# 数据源配置 - 测试环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yibang_erp_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis配置 - 测试环境
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 2000ms

# 日志配置
logging:
  level:
    com.yibang.erp: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

# JWT配置
jwt:
  secret: test-yibang-erp-secret-key-2024
  expiration: 86400000

# 文件上传配置
file:
  upload:
    path: ./uploads/test/
    image:
      max-size: 10MB
      allowed-types: jpg,jpeg,png,gif,webp
      path: images/products
    access:
      base-url: http://localhost:7102/static/

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
